### PR TITLE
Fixes #53

### LINKED ISSUE #53: Graph Coloring Problem
### Aim

To determine all the different ways in which graph can be colored using at most _m_ colors.

### Details

Graph represented by its adjacency matrix.
Colors are represented by the integers 1,2,...,m.

I wish to work on this problem in C++ language.
Please assign this to me.

### PR DESCRIPTION
**Pull request by Karnika06**
### Description:

Added Graph coloring problem code i.e. to determine all the different ways in which graph can be colored using at most m colors. I have used Backtracking for this problem.

### Details:

- Graph represented by its adjacency matrix.
- Colors are represented by the integers 1,2,...,m.

I have used C++ language for this problem.
This problems issue number is #53 .

### CODE REVIEW

**Review by sakshigoel19 — COMMENTED** [review]
Hey @Karnika06 Can you add the readme.md file of the problem in graph folder. Also, kindly format the code according to our guidelines for comments and indentation.

**Comment by Karnika06** [comment]
Okay. Will do it soon

**Comment by Karnika06** [comment]
@sakshigoel19 I have created a new PR with a new branch and made the requested changes and also added the readme.md file.
Please review it.

**Comment by sakshigoel19** [comment]
Sure @Karnika06 , then you can close this pull request.

**Pull request closed without merging**
