### PR TITLE
Fixes #40

### LINKED ISSUE #40: Knight on chess board
I would like to contribute c++ code for Knight on chess board problem.

### PR DESCRIPTION
**Pull request by ReshuKumari**
Adding  C++ code for Knight on chess board problem.

### CODE REVIEW

**Comment by ReshuKumari** [comment]
@Vanshikagarg17 ptal.

**Review by sakshigoel19 — COMMENTED** [review]
Looks good to me.

**Review by v-vanisha — COMMENTED** [review]
Reviewed, no changes required.

**Comment by ReshuKumari** [comment]
@Ananyaas @Shriyanshidixit PTAL!

**Review by Vanshikagarg17 — APPROVED** [review]

**Pull request merged**
