### PR TITLE
Cpp code added for intersection of linked list

### LINKED ISSUE #130: Intersection of Two Linked Lists

### PR DESCRIPTION
**Pull request by Ridhikalra**
hey @Ananyaas ,
This pull request has the required changes for the task completion.
Kindly review it and let me know the changes(if required).
Fixes #130

### CODE REVIEW

**Review by sparshiigupta — CHANGES_REQUESTED** [review]
Hey @Ridhikalra !
Two linked lists intersect when they have a common node(common address). So compare according to address and not according to data. Also, according to guidelines,add 2 testcases at the end of your code.

**Review by v-vanisha — CHANGES_REQUESTED** [review]
Hey @Ridhikalra, You need to add comments as well in your code.  Kindly go through the guidelines and make changes wherever required.

**Comment by Ridhikalra** [comment]
hi @sparshiigupta,
I have made some changes. Kindly review it and let me know if it is correct or not.

**Review by sparshiigupta — COMMENTED** [review]
@Ridhikalra Kindly add comments in your code. Rest everything is perfect.

**Review by sparshiigupta — APPROVED** [review]
LGTM !

**Review by v-vanisha — APPROVED** [review]
LGTM

**Review by sakshigoel19 — APPROVED** [review]
LGTM!

**Review by Vanshikagarg17 — APPROVED** [review]

**Pull request merged**
