### PR TITLE
Added code for Rotate Array problem(in Java)

### LINKED ISSUE #135: Rotate Array Problem
Aim: Given an unsorted array arr[] of size N, rotate it by D elements in the counter-clockwise direction.

### PR DESCRIPTION
**Pull request by swatigupta121**
Fixes #135

### CODE REVIEW

**Review by sparshiigupta — COMMENTED** [review]
Hey @swatigupta121 !
@Khushipm has created a PR for this problem in java. You can add C++ solution to this problem.

**Comment by swatigupta121** [comment]
Hey @sparshiigupta. Please review it once again. I have made the required changes.

**Review by sparshiigupta — APPROVED** [review]
LGTM !

**Review by sakshigoel19 — APPROVED** [review]

**Review by nishtha-01 — APPROVED** [review]
LGTM

**Comment by Ananyaas** [comment]
LGTM

**Comment by Ananyaas** [comment]
@Vanshikagarg17

**Review by Ananyaas — APPROVED** [review]

**Review by Vanshikagarg17 — APPROVED** [review]

**Pull request merged**
