### PR TITLE
To_Change_An_Expression_From_Infix_to_Postfix.c

### LINKED ISSUE #133: To change a Expression from Infix to Postfix

### PR DESCRIPTION
**Pull request by priyanshiparolia**
fixes #133

### CODE REVIEW

**Review by v-vanisha — APPROVED** [review]
LGTM

**Review by nishtha-01 — APPROVED** [review]
LGTM

**Review by sparshiigupta — CHANGES_REQUESTED** [review]
Hey @priyanshiparolia !
Your code gives following warnings:
- In function 'pop': incompatible implicit declaration of built-in function 'exit'
-  In function 'main': 'return' with a value, in function returning void
kindly remove them.

**Comment by priyanshiparolia** [comment]
fixed it

**Review by sparshiigupta — APPROVED** [review]
LGTM !

**Comment by Ananyaas** [comment]
LGTM @Vanshikagarg17

**Review by Vanshikagarg17 — APPROVED** [review]

**Pull request merged**
